name: monorepo-split

on:
  push:
    branches:
      - main

jobs:
  split-monorepo:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - first-package
          - second-package

    steps:
      - uses: actions/checkout@v4
      
      - name: Split for ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/laravel/${{ matrix.package }}'
          repository_organization: 'honedlabs'
          repository_name: '${{ matrix.package }}'
          user_name: "jdw5"
          user_email: "josh@joshua-wallace.com"
          branch: "main"
          repository_host: "github.com"
          repository_username: "${{ github.actor }}"
          repository_password: "${{ secrets.ACCESS_TOKEN }}"