name: monorepo-split

on:
  push:
    branches:
      - main

jobs:
  split-monorepo:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - first-package
          - second-package

    steps:
      - uses: actions/checkout@v4

      # Create repository if it doesn't exist
      - name: Create repository
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/honedlabs/repos \
            -d '{
              "name": "${{ matrix.package }}",
              "private": false,
              "auto_init": true,
              "description": "Split from monorepo"
            }'

      - name: Split for ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/laravel/${{ matrix.package }}'

          repository_organization: 'honedlabs'
          repository_name: '${{ matrix.package }}'

          user_name: "jdw5"
          user_email: "josh@joshua-wallace.com"
          repository_host: "https://${{ secrets.ACCESS_TOKEN }}@github.com"